# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: purplesquad
site_url: https://purplesquad.io/

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    scheme: slate